# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev

pool:
  vmImage: ubuntu-latest

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    - name: branchDestino
      value: 'main'
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    - name: branchDestino
      value: 'qa'
  - ${{ else }}:
    - name: branchDestino
      value: $(Build.SourceBranchName)

steps:
- checkout: self
  path: "s/inicial"

- script: |
    echo "---------------------------------------"
    rm azure-pipelines.yml
    mv mirror-pipelines.yml azure-pipelines.yml
    rm validacion-pipelines.yml
    rm -r .git
    echo "---------------------------------------"
  displayName: "Configuracion repo origen"

- script: |
    cd ..
    git config --global user.email "jib8@msn.com"
    git config --global user.name "Jorge Borja"
    cd final
    git fetch
    ls

- script: |
    cd ../final
    git branch
    git checkout -b $(branchDestino) origin/$(branchDestino)
    ls
    echo "--------------------------------"
    git pull origin $(branchDestino)
    ls

- script: |
    cd ../final
    cp -rf ../inicial/* .
    ls
    git status
    git add .

- script: |
    cd ../final
    git commit -m "Cambio para ID $(Build.BuildId)"
    git push origin $(branchDestino)
  displayName: "Clonacion del repositorio"