# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: FlutterInstall@0
  displayName: "Install Flutter SDK"
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  displayName: "Build application"
  inputs:
    target: apk
    projectDirectory: '$(Build.SourcesDirectory)'

- task: CopyFiles@2
  displayName: "Copy app to staging directory"
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: "Publish Android file"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.Repository.Name) apk'
    publishLocation: 'Container'