name: presentation
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  domain:
    path: ./modules/domain
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  get_it: ^7.2.0
  infrastructure:
    path: ./modules/infrastructure
  injectable: ^2.1.0
  intl: ^0.18.0
  test_cov_console: ^0.2.2

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/loading.png
    - lib/assets/images/network_issue.png
    
  fonts:
    - family: Pathway Gothic One
      fonts:
        - asset: lib/assets/fonts/PathwayGothicOne-Regular.ttf
