include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**, lib/**.g.dart, lib/**.module.dart] 
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    avoid_returning_this: false